### PR TITLE
Fixes #19363 - Filter hosts and reports by rule results

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
https://github.com/theforeman/foreman/pull/5890 is needed for tests to pass

**Comment by xprazak2** [comment]
[test foreman_openscap]

**Comment by xprazak2** [comment]
[test foreman_openscap]

**Comment by xprazak2** [comment]
1. I opened https://github.com/theforeman/theforeman.org/pull/1169 which covers all the search queries we have.

2. The js part of helper for facts is not reusable, but we can go crazy with js once we turn this into a webpacked plugin ;-)

3. I added action buttons leading to host search based on rule, current look: 



4. I would not drop the column, I find the rule name useful. The truncation with tooltip is not helpful if you want to copy it, but I imagine we will be able to expand to the full name as facts do it in the future.

**Comment by ares** [comment]
after a quick discussion, we'll just drop truncate entirely and then this is good to go

**Comment by xprazak2** [comment]
The rule name is now shown in full.

**Comment by ares** [comment]
this will go to 0.11, with the change of the order, applying following is sufficient
```diff
diff --git a/app/helpers/arf_reports_helper.rb b/app/helpers/arf_reports_helper.rb
index 412d1ab..c507f27 100644
--- a/app/helpers/arf_reports_helper.rb
+++ b/app/helpers/arf_reports_helper.rb
@@ -80,8 +80,8 @@ module ArfReportsHelper
   end
 
   def host_search_by_rule_result_buttons(source)
-    action_buttons(display_link_if_authorized(_('Hosts passing this rule'), hash_for_hosts_path(:search => "passes_xccdf_rule = #{source}")),
-                   display_link_if_authorized(_('Hosts othering this rule'), hash_for_hosts_path(:search => "others_xccdf_rule = #{source}")),
-                   display_link_if_authorized(_('Hosts failing this rule'), hash_for_hosts_path(:search => "fails_xccdf_rule = #{source}")))
+    action_buttons(display_link_if_authorized(_('Hosts failing this rule'), hash_for_hosts_path(:search => "fails_xccdf_rule = #{source}")),
+                   display_link_if_authorized(_('Hosts passing this rule'), hash_for_hosts_path(:search => "passes_xccdf_rule = #{source}")),
+                   display_link_if_authorized(_('Hosts othering this rule'), hash_for_hosts_path(:search => "others_xccdf_rule = #{source}")))
   end
 end

```

**Comment by ares** [comment]
this will now need rebasing :-/

**Comment by xprazak2** [comment]
Rebased + swapped the button order, failing should be on top now.

**Comment by ares** [comment]
could you please rebase? we branched out 0.10 so this one can get in afterwards

**Comment by ares** [comment]
Thanks @xprazak2, great stuff!

**Pull request merged**
