### PR TITLE
Fixes #19242 - Unscope smart proxies

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
I think a slightly better solution would be to set the `User.current = User.anonymous_admin` in the rake task, like we did in https://github.com/theforeman/foreman_templates/pull/46/files

Otherwise users might be using proxies from different organization when they import new content files from UI if I understood it correctly..

**Comment by xprazak2** [comment]
`User.current = User.anonymous_admin` takes care of the issue.

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
Thanks @xprazak2, merging!

**Pull request merged**
