### PR TITLE
Fixes #21038 - unify date formats

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
It seems you will need to include `ApplicationHelper` into `OpenscapProxiesControllerTest` to make the failing test pass. I think we no longer need to import [DateHelper](https://github.com/theforeman/foreman_openscap/blob/master/test/functional/openscap_proxies_controller_test.rb#L4).

**Comment by shiramax** [comment]
@xprazak2 , thanks I still need to import DateHelper because time_ago_in_words is using it.

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
Merging, thanks!

**Pull request merged**
