### PR TITLE
Fixes #21486 - Rename FactoryGirl to FactoryBot

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Looks good, ready for Wed :-) we should watch for any other PR that would introduce new factories but I don't expect any to appear.

**Comment by tbrisker** [comment]
[test]

**Comment by ares** [comment]
@xprazak2 could you please rebase? The rubocop caused some conflicts.

**Comment by xprazak2** [comment]
Rebased

**Comment by ares** [comment]
Tests won't run since master doesn't know FactoryGirl anymore. Could you please trigger custom jenkins job for this PR? I'd do it myself but I'm writing from mobile which makes it quite hard.

**Comment by xprazak2** [comment]
I do not have access to Jenkins, could you kick off the build please?

**Comment by ares** [comment]
triggered at http://ci.theforeman.org/job/test_plugin_pull_request/4284/

**Comment by ares** [comment]
the jenkins job seems to be broken, I ran tests locally and it seems to be all green

```
Finished in 21.075669s, 5.5040 runs/s, 10.9131 assertions/s.
116 runs, 230 assertions, 0 failures, 0 errors, 1 skips
```

therefore merging. Thanks @xprazak2

**Pull request merged**
