### PR TITLE
don't depend on theforeman/stories

### PR DESCRIPTION
**Pull request by evgeni**
this was dropped from core in https://github.com/theforeman/foreman/commit/5e7343ecdad7632a94efa26fcba84889e66b06b4

### CODE REVIEW

**Comment by stejskalleos** [comment]
@evgeni For some reason, I can't rerun GH actions, can you please rebase?

**Comment by evgeni** [comment]
done, let's see what the CI gods say now

**Comment by evgeni** [comment]
seems like a nope for me, but I have no idea what's happening there.

**Comment by stejskalleos** [comment]
Thanks @evgeni @Ron-Lavi

**Pull request merged**
