### PR TITLE
Fixes #20096 - render charts again

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
@xprazak2 would you mind to look? should be small, I'd like to do another release with this fix soon.

**Comment by shlomizadok** [comment]
APJ (I know that u missed me... 😉 )

**Comment by ares** [comment]
[test]

**Comment by xprazak2** [comment]
Looking good, but I think we need one additional change on [the reports page](https://github.com/theforeman/foreman_openscap/blob/master/app/views/arf_reports/show.html.erb#L1)

**Comment by ares** [comment]
Good catch, added, please take another look.

**Comment by xprazak2** [comment]
Merging, thanks!

**Pull request merged**
