### PR TITLE
Fixes #16325 - policy delete should remove association

### PR DESCRIPTION
**Pull request by ranjan**

### CODE REVIEW

**Comment by ares** [comment]
why is this desired? does it mean that deleting policy would delete hostgroup/host?

**Comment by ranjan** [comment]
Added Fix for broken test of PR#189

**Comment by ares** [comment]
I see now, I missed `:through` on which only the association is deleted. Since there can be left overs in this table already, could you add a migration that would delete those?

Also, is the test fix required because of this change? It seems broken for longer time right? In such case, could you please create a separate PR for that?

**Comment by ares** [comment]
btw I tested the change, works as expected

**Comment by ares** [comment]
Thanks, works nicely, merging! (tests failed only on https://github.com/theforeman/foreman_openscap/pull/197)

**Pull request merged**
