### PR TITLE
Fixes #27378 - make deploy options clickable

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
This makes the label clickable and selecting the option, but keeping the little popover icon just displaying the help text without selecting the radio.

**Comment by xprazak2** [comment]
Works, the tooltip help is moved now, do we need an additional styling?

tooltip

**Comment by ares** [comment]
The reason was I had too small width :-) I added float and also adjusted the width so it's consistent with how we use it elsewhere. Ready for rereview.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
