### PR TITLE
Fixes #15698 - fix syntax error

### PR DESCRIPTION
**Pull request by enricomingardo**
Fixes #15698 - fix syntax error

### CODE REVIEW

**Comment by ares** [comment]
Thanks for the patch, could you please modify the commit message so the foreman-bot can link it with redmine issue? Just add "Fixes " in the beginning of it and foreman-bot will be happy.

**Comment by enricomingardo** [comment]
I'm sorry @ares can you help me? Where I'm wrong?

**Comment by ares** [comment]
@enricomingardo the second commit looks good now, but the PR contains two commits now. You can drop the first one using rebase
```sh
git rebase -i HEAD^ # this open editor where you just delete the line with first commit
git push -f # pushes new single commit to github
```

Next time to change only to commit message you can run `git commit --amend` and then `git push -f`
if you won't be able to make it, I can squash it during merge. Also I've triggered automated [test]

Please let me know if you need any help or I should merge the PR manually picking only the second commit.

**Comment by ohadlevy** [comment]
[test]

**Comment by shlomizadok** [comment]
Tested locally. (won't wait for Jenkins).
Thanks a lot @enricomingardo !

**Pull request merged**
