### PR TITLE
fixes #11424 - Add load_report.js to engine.rb assets:precompile

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by domcleal** [comment]
https://github.com/theforeman/foreman_plugin_template/blob/master/lib/foreman_plugin_template/engine.rb#L41-L55 is an alternative way of doing it for very simple cases (where all assets are top-level and won't require each other).  Or you could build a test around the technique.

**Comment by shlomizadok** [comment]
@domcleal thank you so much for this! would love if you could ack.

**Comment by domcleal** [comment]
It reads correctly, but I haven't tested that they are indeed precompiled.

**Comment by shlomizadok** [comment]
@domcleal -- thanks. I've tested those. @xprazak2 / @ares - mind verifying?

**Comment by xprazak2** [comment]
@shlomizadok: seems to be working for me, like [this](http://i.imgur.com/Y0Rv8Rt.png)

**Comment by shlomizadok** [comment]
Thanks for testing @xprazak2 
Thanks for your insight @domcleal 
Merging

**Comment by domcleal** [comment]
You're missing policy.css in that screenshot?

**Comment by xprazak2** [comment]
hmm, maybe I am. Let me do a re-run.

**Comment by shlomizadok** [comment]
the problem is that the file name is ```policy.css.scss``` and assets precompile expects ```policy.css```
As there is no real use of sass capabilities, I'm gonna rename that file in a separate pr.

**Pull request merged**
