### PR TITLE
Fixes #33015 - Add OVAL Content show page

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Works well, do you plan to add anything else here? E.g. the delete button, list of policies that use it or is that planned in separate PR?

**Comment by ares** [comment]
Few other random thougst: 
* perhaps also link to "define a new policy based on this content" would be nice :-)
* the URL (for url based content) could be clickable and open a new tab
* the uploaded content should be download-able like we allow for SCAP content, for investigation purposes

**Comment by xprazak2** [comment]
No immediate plans to add more right now, though all the things you mentioned would be nice additions - I'll turn them into Redmine issues for now. I am just not sure about redirecting to the url since those files are bzipped...

**Review by ares — APPROVED** [review]
Thanks @xprazak2, merging!

**Pull request merged**
