### PR TITLE
Hook rake tests on test:plugins

### PR DESCRIPTION
**Pull request by lzap**
See https://github.com/theforeman/foreman/pull/3666

### CODE REVIEW

**Comment by shlomizadok** [comment]
@lzap - can you take a look why [test] is failing?

**Comment by ares** [comment]
[test]

**Comment by lzap** [comment]
Oh it's testing again. If it fails, ping me.

**Comment by ares** [comment]
@lzap ping

**Comment by lzap** [comment]
The core patch was not yet merged guys :-) Cool, stay cool...

**Comment by ares** [comment]
Closing because of inactivity in core PR, please reopen once core PR is done.

**Pull request closed without merging**
