### PR TITLE
Fixes #37755 - drop oval code leftovers in React

### PR DESCRIPTION
**Pull request by MariaAga**
This code is not used anywhere in the repo anymore

### CODE REVIEW

**Comment by ofedoren** [comment]
Thanks, @MariaAga, I'm afraid there are more things to drop. Should we drop everything that's not used or we're dropping only "broken/bothering" parts?

**Comment by MariaAga** [comment]
I found this while updating to pf5, and these were an effort to update, so deleting them looks easier.
I didn't see anything else thats unused, but I only checked a few things

**Review by adamruzicka — APPROVED** [review]
Some dropped parts are still better than no dropped parts, let's get this in

**Comment by adamruzicka** [comment]
Thank you @MariaAga !

**Pull request merged**
