### PR TITLE
 Fixes #18998 - UX improvements

### PR DESCRIPTION
**Pull request by ares**
based on https://github.com/theforeman/foreman_openscap/pull/385, implemented all things besides arf report icons for status, that needs more thinking

### CODE REVIEW

**Comment by xprazak2** [comment]
Works nicely, could you add pagination for tailoring files and policies as well?

**Comment by ares** [comment]
Added, please take another look. Also we'll need to update the manual for 1.0 so that the documentation button links to something that exists

**Comment by xprazak2** [comment]
APJ

**Comment by xprazak2** [comment]
@ares, could you create an issue in Redmine for the status icons that are not a part of this fix so that we do not lose track of that item?

**Comment by ares** [comment]
Yeah, opened as https://projects.theforeman.org/issues/26780, thanks for the review

**Pull request merged**
