### PR TITLE
Fixes #34134 - removing the increment on the day of the week

### PR DESCRIPTION
**Pull request by fsbano**
Before version 6 it was necessary to make the increment now it is no longer due to the API upgrade
Monday is starting now with the value 1 which was previously the value 0

### CODE REVIEW

**Comment by fsbano** [comment]
Hello Everybody,

As you can see below, there is no need to increase

DAYS_INTO_WEEK | = | { sunday: 0, monday: 1, tuesday: 2, wednesday: 3, thursday: 4, friday: 5, saturday: 6 }
WEEKEND_DAYS    | = | [ 6, 0 ]

https://api.rubyonrails.org/v6.1.4/classes/DateAndTime/Calculations.html

Best Regards,
Fabio Sbano

**Comment by xprazak2** [comment]
Nice catch, rubocop failures unrelated. @lzap, @Ron-Lavi, I do not have a setup right now, could you test?

**Comment by fsbano** [comment]
Hello Everybody,

Any Updates?

Best Regards,
Fabio Sbano

**Comment by Ron-Lavi** [comment]
Hey @fsbano I will test it soon when my environment will work fully again, though I have no permissions yet to merge, code wise looks good 👍

**Comment by fsbano** [comment]
@Ron-Lavi 

Thank you so much

Happy New Year to everybody

Best Regards,
Fabio Sbano

**Comment by ares** [comment]
tests have been fixed now, can you please rebase so they start passing? thanks

**Comment by ares** [comment]
:+1: from the code perspective, a test would be great but not mandatory

**Comment by fsbano** [comment]
Can i help with anything else?

Best Regards,
Fabio Sbano

**Review by Ron-Lavi — APPROVED** [review]

**Comment by ares** [comment]
Thanks and sorry for delay, merging!

**Pull request merged**
