### PR TITLE
Fixes #11806 - Add Katello::System as assetable asset

### PR DESCRIPTION
**Pull request by shlomizadok**
@stbenjam, mind taking a look too? Thanks

### CODE REVIEW

**Comment by ares** [comment]
@shlomizadok is this still active or do we wait for host unification outcome?

**Comment by shlomizadok** [comment]
@ares - still active.

**Comment by ares** [comment]
so it needs rebasing, since it's open against master and this is still referring to Scaptimony

**Comment by shlomizadok** [comment]
@ares, fixed. thanks

**Comment by ares** [comment]
LGTM

**Comment by shlomizadok** [comment]
@stbenjam / @ehelms - any chance to test this with upstream Katello please (so I won't be the only one who tested this...). Thanks :)

**Comment by ehelms** [comment]
Since @jlsherrill is leading the host unification effort, and dealing a lot with the system's area right now I am going to request he take a look at this. If @jlsherrill passes it back to me, more than happy to test/review.

**Comment by jlsherrill** [comment]
If i remember correctly this was intended as a backport for already released $DOWNSTREAM_PRODUCT, is that still the case?  if it is then we should still test it, otherwise I would not add katello system support as it should be removed in 2.5

**Comment by shlomizadok** [comment]
Closing, as this version is planned for Foreman 1.11 + Katello 2.5

**Pull request closed without merging**
