### PR TITLE
Fixes #20606 - Add missing rabl template for scap content

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Looks fine, could we print title instead of name? Now it only prints message and id. Or is that a hammer-cli-openscap change?

**Comment by xprazak2** [comment]
Yes, some changes on hammer side are definitely needed to print title. For csv, we would need to override the [print_message](https://github.com/theforeman/hammer-cli/blob/master/lib/hammer_cli/output/adapter/csv.rb#L174-L196) from csv output adapter.

**Comment by xprazak2** [comment]
Yes, some changes on hammer side are definitely needed to print title. For csv, we would need to override the [print_message](https://github.com/theforeman/hammer-cli/blob/master/lib/hammer_cli/output/adapter/csv.rb#L174-L196) from csv output adapter.

**Comment by ares** [comment]
Ok, I wonder why `name` was not used in the first place... It would work if we override the method in CreateCommand like this
```ruby
def print_message(msg, msg_params={})
        super(msg, msg_params)
      end
```

But it would contain header saying `Name` so it would be confusing. Let's keep it like this for now, I opened a bug on hammer-cli http://projects.theforeman.org/issues/20744 and merging as it is.

Thanks @xprazak2!

**Pull request merged**
