### PR TITLE
Fixes #16490 - extend hostgroup and host API

### PR DESCRIPTION
**Pull request by ares**
@xprazak2 mind to take a look? Seems like we can use this http://projects.theforeman.org/projects/foreman/wiki/How_to_Create_a_Plugin#Adding-a-Smart-Proxy

with this we even get extended rabl templates

### CODE REVIEW

**Comment by xprazak2** [comment]
It is as you suspected, [Katello](https://github.com/Katello/katello/blob/master/app/controllers/katello/concerns/api/v2/hostgroups_controller_extensions.rb#L7) overrides the doc. 

We should probably move our own [belongs_to](https://github.com/theforeman/foreman_openscap/blob/master/app/models/concerns/foreman_openscap/openscap_proxy_extensions.rb#L6) just to ArfReport.

**Comment by ares** [comment]
Works with https://github.com/Katello/katello/pull/6937

**Comment by xprazak2** [comment]
Works nicely, waiting for Katello PR to be merged.

**Comment by xprazak2** [comment]
@ares, I think we should remove the `:belongs_to` from `OpenscapProxyExtensions` and move it just to `ArfReport`. `BelongsToProxies` sets up the relations to `Host` and `Hostgroup` for us when registering in `Engine`, see my comment above.

**Comment by ares** [comment]
You're right, good catch. Updated.

**Comment by xprazak2** [comment]
Merging, thanks!

**Pull request merged**
