### PR TITLE
Fixes #28251 - Do not assign lone taxonomies to report

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by tbrisker** [comment]
Looking at the code, we should be skipping all reports in core like we do for parameteres

**Comment by ares** [comment]
we include Taxonomix in ArfReport, why do we want to stop assigning lone org/loc here?

**Comment by tbrisker** [comment]
Because reports have taxonomies through hosts, they shouldn't be directly assigned: https://github.com/theforeman/foreman/blob/develop/app/models/report.rb#L16-L17

**Comment by ares** [comment]
Oh, that makes sense. I'll merge this to have a fix in place, but I assume similar patch is needed in core. Thanks @xprazak2!

**Comment by tbrisker** [comment]
a bit late but here is the fix in core: https://github.com/theforeman/foreman/pull/7275/

**Pull request merged**
