### PR TITLE
Fixes #24606 - Fix breadcrumb bar on compliance host page

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs https://github.com/theforeman/foreman/pull/5949 for Resource switcher to suggest only compliance hosts.

**Comment by ares** [comment]
could you please rebase? this is now ready to go in

**Comment by ares** [comment]
this needs another rebase :-/

**Comment by ares** [comment]
Thanks @xprazak2, merging!

**Pull request merged**
