### PR TITLE
Fixes #14561 - Updating parameters for foreman_scap_client in after_save

### PR DESCRIPTION
**Pull request by xprazak2**
This continues where #160 left off.

### CODE REVIEW

**Comment by ares** [comment]
I guess that tests are failing because of Rails 4.2 incompatibilities.

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
@ares lgtm. Please ack

**Comment by xprazak2** [comment]
I rebased on master

**Comment by ares** [comment]
Sorry it took me a while, I've tested it and it works great also when associating the proxy via hostgroup. Thanks @xprazak2, merging.

**Pull request merged**
