### PR TITLE
Fixes #14253 - Avoid mass assignment for policy widgets

### PR DESCRIPTION
**Pull request by xprazak2**
I also removed useless helper. We do not even have `ForemanOpenscap::PolicyDashboard::Manager`.

### CODE REVIEW

**Comment by shlomizadok** [comment]
:+1:

**Comment by ares** [comment]
I suppose this is required for Foreman 1.12+ only, correct?

**Comment by xprazak2** [comment]
I believe this is Rails 4.2 related, there is a fix in [core](https://github.com/theforeman/foreman/commit/38987e042c1bdd55b259ee6a7fa34403341c8d80) that made 1.11.1

**Comment by ares** [comment]
Fixes the issue for me, thanks @xprazak2, merging.

**Comment by ares** [comment]
Ooops I missed that you've used Foreman core issue # for this PR. Next time please create separate issue under Foreman Openscap project.

**Comment by shlomizadok** [comment]
Also, I believe this needs to be tagged for Foreman >= 1.12?

2016-06-21 15:13 GMT+03:00 Marek Hulán <notifications@github.com>:

**Comment by ares** [comment]
I think it should be 1.11 compatible, not tested. With next release we can bump the version to 0.6 and start requiring 1.12 though.

**Pull request merged**
