### PR TITLE
Fixes #17464 - Use digest to detect scap_file changes

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by shlomizadok** [comment]
@xprazak2 - rebase please :)

**Comment by xprazak2** [comment]
Rebased

**Comment by xprazak2** [comment]
[test]

**Comment by ares** [comment]
Works, before we merge, I wonder if we should do one smart_proxy_openscap release before we have this in. I suppose users will first upgrade their Foreman instances and of the Foreman configures new download path, smart proxy won't be able to serve it until updated, correct?

**Comment by xprazak2** [comment]
Correct, if foreman_openscap is updated and configures a client with a new `download_path` (containing a hash), then proxy will not be able to serve unless updated as well.

**Comment by ares** [comment]
Thanks @xprazak2, merging

**Pull request merged**
