### PR TITLE
rename policy.css.scss to policy.css

### PR DESCRIPTION
**Pull request by shlomizadok**
@xprazak2 - mind testing that it is now added?

### CODE REVIEW

**Comment by shlomizadok** [comment]
image
and 
image
locally

**Comment by xprazak2** [comment]
this time for real: 



sorry about earlier, I did not check if there was .css file because it did not cross my mind it would not get picked up since all .js files were there

**Comment by shlomizadok** [comment]
Will merge and release when tests will be green.
Thanks for testing @xprazak2

**Comment by shlomizadok** [comment]
All tests have [passed](http://ci.theforeman.org/job/test_plugin_pull_request/1169/), yet jenkins is hung.
merging

**Pull request merged**
