### PR TITLE
Fixes #12524 - Add a migration to ensure mysql is creating a binary i…

### PR DESCRIPTION
**Pull request by shlomizadok**
…n the right size

### CODE REVIEW

**Comment by ares** [comment]
LGTM

**Comment by ShimiTaNaka** [comment]
If I'm not mistaking, this fix is incompatible with version 0.4.3 of the plugin, Can it be adapted?

**Comment by shlomizadok** [comment]
@ShimiTaNaka - please see https://github.com/OpenSCAP/scaptimony/pull/32 for 0.4.3

**Comment by ares** [comment]
0.4.* version used scaptimony for storing content (which seems to have the same [bug](https://github.com/OpenSCAP/scaptimony/blob/master/db/migrate/20141214112917_add_scap_file_to_scap_content.rb#L3))

**Pull request merged**
