### PR TITLE
Fixes #31423 - Update port param type

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
should we rather call save! to know if this failed? also what if the migration has been already applied? the bug does not seem to be triggered during the migration

**Comment by xprazak2** [comment]
I added a new migration to make sure it runs.

**Review by ares — APPROVED** [review]
Thanks @xprazak2, merging!

**Comment by ares** [comment]
the tests fail on rubocop

**Pull request merged**
