### PR TITLE
Fixes #28609 - Remove fix for skipping lone taxonomies assignment

### PR DESCRIPTION
**Pull request by maccelf**
Assigning lone taxonomies was fixed in core, we can now remove the fix we have in arf_reports_controller.

### CODE REVIEW

**Comment by ares** [comment]
I think that makes sense, the original fix for the record is https://github.com/theforeman/foreman/pull/7275/files which now shortcircuit the `assign_lone_taxonomies` for reports from core if I understand correctly.

[ok to test]

@maccelf could you please confirm that's the logic behind this change?

**Comment by maccelf** [comment]
> I think that makes sense, the original fix for the record is https://github.com/theforeman/foreman/pull/7275/files which now shortcircuit the `assign_lone_taxonomies` for reports from core if I understand correctly.
> 
> [ok to test]
> 
> @maccelf could you please confirm that's the logic behind this change?

@ares yes, i think is that the logic behind this change

**Comment by xprazak2** [comment]
Looks good, the tests will not pass for now due to puppet changes.

**Comment by ares** [comment]
Ok, :+1: from me, leaving up to @xprazak2 to merge when we're ready.

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
