### PR TITLE
Fixes #20364 - Inclusion of hostgroups in compliance policy

### PR DESCRIPTION
**Pull request by vision2910**

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by xprazak2** [comment]
Works for me, will merge when Jenkins turns green.

**Comment by ares** [comment]
for some reason, all tests are red with "ActiveRecord::RecordInvalid: Validation failed: Name has already been taken", let's try once again [test]

**Comment by ares** [comment]
This was fixed in core, rerunning the [test]

**Comment by xprazak2** [comment]
We finally managed to fix our tests, merging. Sorry it took so long.

**Pull request merged**
