### PR TITLE
Fixes #12616 - Add more details to Arf report view

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by shlomizadok** [comment]
After the change it looks like:
image
When clicking on the "info" icon it expands to more details
image

@kybaker, @ohadlevy - would love your comments

**Comment by shlomizadok** [comment]
Note to reviewers: First commit is the actual change, second commit is Rubocop fixes only.

**Comment by shlomizadok** [comment]
@xprazak2 - thanks for reviewing. Fixed your comment.

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
wtf is wrong with the rebasing???

**Comment by shlomizadok** [comment]
[test]

**Comment by shlomizadok** [comment]
@xprazak2 - mind giving this another spin please?

**Comment by xprazak2** [comment]
Sure, I will test again.

**Comment by xprazak2** [comment]
Working like a charm now, git says there are 2 more commits now - not sure how they ended up there, but if it is ok, then I have no more comments.

**Comment by shlomizadok** [comment]
Yeah, not sure about that. merged manually

**Pull request merged**
