### PR TITLE
fixes #11604 - remove 'distribute scap content' banner

### PR DESCRIPTION
**Pull request by shlomizadok**

### CODE REVIEW

**Comment by ares** [comment]
When I upload new SCAP content, there's still a bubble "Notice: You need to install OpenSCAP on your hosts, and upload this content to the hosts as well.", I'd say the second part is also not necessary. 

Also when you edit the policy, there's still bubble with text "Notice: Ensure the selected SCAP content exists on your hosts. SCAP content file should be /var/lib/openscap/content/3fc6fa833e8bb6a0cc76f1909e3ab329dcb4a2efdfb75ec898a9cac912659f4e.xml on your clients."

When I create new policy, after selecting a content, I still see the information, not in bubble though.

scap

**Comment by shlomizadok** [comment]
@ares - Fixed & rebased. Thanks

**Comment by ares** [comment]
> When I upload new SCAP content, there's still a bubble "Notice: You need to install OpenSCAP on your hosts, and upload this content to the hosts as well.", I'd say the second part is also not necessary.

doesn't seem to be addressed or does it still make sense to upload the content to the hosts in some cases?

**Comment by shlomizadok** [comment]
Sorry, missed that earlier. removed now.

**Comment by ares** [comment]
:+1: will merge pending tests

**Comment by ares** [comment]
Merging, thanks @shlomizadok!

**Pull request merged**
