### PR TITLE
Fixes #16123 - fixes error in widget if policy is missing

### PR DESCRIPTION
**Pull request by orrabin**

### CODE REVIEW

**Comment by shlomizadok** [comment]
LGTM

**Comment by shlomizadok** [comment]
@xprazak2 @ares - this seems ready to merge. Please ack (or merge...)

**Comment by xprazak2** [comment]
Seems like `link_to` will now require its arguments in parens because of ternary operator:

**Comment by orrabin** [comment]
@xprazak2 thanks, I fixed the link. 
This is the widget without a policy:

image

**Comment by xprazak2** [comment]
@orrabin, it works for me now. I think we can merge when the tests turn green.

**Comment by shlomizadok** [comment]
Merging. Thanks @orrabin and @xprazak2 for testing

**Pull request merged**
