### PR TITLE
Fixes #15489 - keep host assets associated with policy

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by ares** [comment]
please see a [redmine](http://projects.theforeman.org/issues/15489) issue for detailed explanation

**Comment by shlomizadok** [comment]
Will merge when Jenkins with end. Great catch.

**Comment by shlomizadok** [comment]
Tested: :+1:

**Comment by shlomizadok** [comment]
Merging. Thanks @ares++

**Pull request merged**
