### PR TITLE
Fixes #24607 - Remove 'notice' from controllers

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by ares** [comment]
Mind to also bump min foreman version to 1.20 in lib/foreman_openscap/engine.rb? Right now it says 1.18, this will also need to bump version to 0.11

**Comment by xprazak2** [comment]
Updated.

**Comment by ares** [comment]
[test foreman_openscap]

**Comment by ares** [comment]
The failures are unrelated, merging. Thanks @xprazak2

**Pull request merged**
