### PR TITLE
Fixes #18734 - Use Rex feature to run scans

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
This may also be useful to do in bulk from hosts/index page. Is remote execution planning on supporting it in some way or should I add a button?

**Comment by ares** [comment]
There's already a bulk action "Run Job" that takes you to REX form. There's just one manual step to select the job you want to run, in this case it would be scap scan. Personally I think that is good enough, I'd like to avoid adding a lot more custom bulk actions to the menu that already contains more than 10 items.

**Comment by xprazak2** [comment]
OK, sounds reasonable.

**Comment by ares** [comment]
Somehow tests seem to be broken by this, but form quick scan code looks good.

**Comment by ares** [comment]
[test]

**Comment by ares** [comment]
Tests are green, thanks @xprazak2, merging!

**Pull request merged**
