### PR TITLE
Fixes #26604 - Fix layout on policy dashboard

### PR DESCRIPTION
**Pull request by xprazak2**

### CODE REVIEW

**Comment by xprazak2** [comment]
needs https://github.com/theforeman/foreman/pull/6675

**Comment by ares** [comment]
After core gets in, please don't bump major version number (1.0) and Foreman dependency in engine to 1.23 (if that's in for 1.23). Also there's failing rubocop now.

```
Inspecting 107 files
...............................C...........................................................................

Offenses:

/home/jenkins/workspace/foreman_openscap-pull-request/database/postgresql/label/fast/ruby/2.5/plugin/app/models/concerns/foreman_openscap/smart_proxy_extensions.rb:9:20: C: Style/MutableConstant: Freeze mutable objects assigned to constants.
      PORT_MATCH = /:(\d+)\z/
                   ^^^^^^^^^^
```

**Comment by xprazak2** [comment]
Rubocop passes and I increased the `requires_foreman` to ` 1.22 as the required change was merged in core.

**Comment by ares** [comment]
drop the rubocop changes pls

**Comment by xprazak2** [comment]
Rebased, failing usergroup audit tests.

**Pull request merged**
