### PR TITLE
Fixes #33351 - Introduce foreman-rubocop

### PR DESCRIPTION
**Pull request by lzap**
I am unable to run Rubocop autocorrection via the provided rake task.

This switches to the new approach that Ondřej created a year ago:

https://github.com/theforeman/theforeman-rubocop

Rubocop can be now executed normally via "bundle exec". Updated GHA.

I copied config from bootdisk, it is very light on Style and Naming rules. I also regenerated TODO, there are many TODO items mostly from Rails rules.

### CODE REVIEW

**Comment by lzap** [comment]
Yeah I messed up GHA YAML. Rebased.

**Comment by lzap** [comment]
I fixed Rubocop finally, but now tests are failing because of:

```
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/graphql-1.8.18/lib/graphql/schema/mutation.rb:70: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/graphql-1.8.18/lib/graphql/schema/member/has_fields.rb:51: warning: The called method `field' is defined here
rake aborted!
NameError: uninitialized constant Proxy
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/smart_proxy_dynflow-0.5.2/lib/smart_proxy_dynflow/task_launcher_registry.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/smart_proxy_dynflow-0.5.2/lib/smart_proxy_dynflow.rb:3:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/smart_proxy_remote_execution_ssh-0.4.1/lib/smart_proxy_remote_execution_ssh.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/foreman_remote_execution_core-1.5.0/lib/foreman_remote_execution_core.rb:2:in `<module:ForemanRemoteExecutionCore>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/foreman_remote_execution_core-1.5.0/lib/foreman_remote_execution_core.rb:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/foreman_ansible_core-4.1.2/lib/foreman_ansible_core.rb:4:in `<top (required)>'
/home/jenkins/workspace/foreman_openscap-pull-request/database/postgresql/label/fast/ruby/2.7/foreman/config/application.rb:58:in `<top (required)>'
/home/jenkins/workspace/foreman_openscap-pull-request/database/postgresql/label/fast/ruby/2.7/foreman/Rakefile:1:in `require'
/home/jenkins/workspace/foreman_openscap-pull-request/database/postgresql/label/fast/ruby/2.7/foreman/Rakefile:1:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/bin/ruby_executable_hooks:24:in `eval'
/usr/local/rvm/gems/ruby-2.7.0@foreman_openscap-pull-request-0/bin/ruby_executable_hooks:24:in `<main>'
(See full trace by running task with --trace)
```

**Comment by xprazak2** [comment]
I think that is because of core gems removal on the Foreman side - seems like you still have foreman_ansible_core and foreman_remote_execution_core in foreman/bundler.d - things should work again once you remove them.

Looks like gh actions are greeen, are we good to merge here?

**Comment by xprazak2** [comment]
Thanks!

**Pull request merged**
