### PR TITLE
Refs #20666 - fix the string

### PR DESCRIPTION
**Pull request by ares**

### CODE REVIEW

**Comment by xprazak2** [comment]
Needs a string change in [test](https://github.com/theforeman/foreman_openscap/blob/master/test/unit/policy_test.rb#L208) as well.

**Comment by ares** [comment]
Thanks @xprazak2, should be fixed now.

**Comment by xprazak2** [comment]
Looks good @ares. We can either merge this and add to (7.5 cherry-picks)[https://github.com/theforeman/foreman_openscap/pull/287] or make it a separate issue. What do you think?

**Comment by ares** [comment]
I will happily add it to 7.5 cherrypicks after you merge it :-)

**Pull request merged**
