### PR TITLE
Fixes #20444 - Add validations for uniqueness content title

### PR DESCRIPTION
**Pull request by shiramax**

### CODE REVIEW

**Comment by xprazak2** [comment]
[test]

**Comment by ares** [comment]
Tests won't run until we get master tests stable

**Comment by xprazak2** [comment]
@shiramax: I think you'll need to make a change in the [factory](https://github.com/theforeman/foreman_openscap/blob/master/test/factories/scap_content_related.rb#L5), something like:

```ruby
f.sequence(:title) { |n| "scap_content_title_#{n}" }
``` 

could work.

**Comment by shiramax** [comment]
@xprazak2 Done, I also added migrations for the title uniqueness.

**Comment by xprazak2** [comment]
[test]

**Comment by ares** [comment]
Failures seems to be caused by new rails 5 migration syntax. `Migration[5.0]` does not seem to work, should the 5.0 tag be removed?

**Comment by shiramax** [comment]
@ares Done.

**Comment by xprazak2** [comment]
[test]

**Comment by shiramax** [comment]
[test]

**Comment by xprazak2** [comment]
The migration error is probably not intermittent, when I looked at my db, I got:



the table was renamed in the past but the index names were not, that seems to cause the migration to fail now. I would try to get the index name from table and then remove it by name.

**Comment by xprazak2** [comment]
[test]

**Comment by shiramax** [comment]
[test]

**Comment by xprazak2** [comment]
[test]

**Comment by ares** [comment]
Test failures unrelated, LGTM. Leaving for @xprazak2 to finish the proper review that he started :-)

**Comment by xprazak2** [comment]
Test failure is indeed unrelated, migrations no longer fail. I think we are good here. Thanks @shiramax!

**Pull request merged**
