### PR TITLE
Fixes #10549 - show host name only if host exists

### PR DESCRIPTION
**Pull request by shlomizadok**
Needs to be backported to maint-foreman17 too

### CODE REVIEW

**Comment by ares** [comment]
LGTM, not tested

**Comment by ares** [comment]
oh yeah, it was a module so you it must be alias, I think you can squash both commits and it's ready

**Comment by ares** [comment]
Works nicely, merging. Thanks @shlomizadok.

**Comment by ares** [comment]
@shlomizadok would you mind CP to maint-foreman17?

**Comment by shlomizadok** [comment]
Done

**Pull request merged**
